
# File: .github/workflows/repo-sync.yml
name: yangtingxiao-QuantumultX-master # 修改此处
on:
  schedule:
    - cron: '45 16 * * *' # 执行时间 # 修改此处
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: yangtingxiao-QuantumultX-master #运行过程中的名称 # 修改此处
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yangtingxiao/QuantumultX.git" #克隆对方仓库的git地址 # 修改此处
          source_branch: "master" # 克隆对方仓库的分支 # 修改此处
          destination_branch: "yangtingxiao-QuantumultX-master" #新建一个你自己的远程分支 # 修改此处
          github_token: ${{ secrets.PAT }}
