name: i-chenzhe-qx-main # Task name
on:
  issues:
    types:  [opened]
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-scripts
    
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: i-chenzhe-qx-main # Task name
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/i-chenzhe/qx.git" # Git address of this repository
          source_branch: "main" # Branch of this repository
          destination_branch: "i-chenzhe-qx-main" # Create your own branch
          github_token: ${{ secrets.PAT }}
