# File: .github/workflows/repo-sync.yml
name: shylocks-Loon-master
on:
  schedule:
    - cron: '5 0-16,23 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync shylock Loon
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://bitbucket.org/jd-study/shylocks.git"
          source_branch: "master" # 克隆对方仓库的哪一个分支
          destination_branch: "shylock-Loon-master" #新建一个你自己库里远程分支的名称
          github_token: ${{ secrets.PAT }}
